# Generated by Django 3.2.8 on 2021-10-15 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=100, null=True)),
                ('official_link', models.URLField(blank=True, max_length=500, null=True)),
                ('activity', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('rating', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=200, null=True)),
                ('p_image', models.URLField(blank=True, max_length=500, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('b_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Wifi_perfuma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classname', models.CharField(blank=True, max_length=500, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=300, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Similar_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('p_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(blank=True, max_length=300, null=True)),
                ('summer', models.CharField(blank=True, max_length=300, null=True)),
                ('spring', models.CharField(blank=True, max_length=300, null=True)),
                ('fall', models.CharField(blank=True, max_length=300, null=True)),
                ('day', models.CharField(blank=True, max_length=300, null=True)),
                ('night', models.CharField(blank=True, max_length=300, null=True)),
                ('p_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Product_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_note', models.CharField(blank=True, max_length=500, null=True)),
                ('middle_note', models.CharField(blank=True, max_length=500, null=True)),
                ('base_note', models.CharField(blank=True, max_length=500, null=True)),
                ('others', models.CharField(blank=True, max_length=500, null=True)),
                ('p_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Popular_products_by_brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('b_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.PositiveIntegerField(blank=True, null=True)),
                ('night_out', models.PositiveIntegerField(blank=True, null=True)),
                ('evening', models.PositiveIntegerField(blank=True, null=True)),
                ('leisure', models.PositiveIntegerField(blank=True, null=True)),
                ('daily', models.PositiveIntegerField(blank=True, null=True)),
                ('business', models.PositiveIntegerField(blank=True, null=True)),
                ('p_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Most_used_notes_by_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('accord', models.PositiveIntegerField(blank=True, null=True)),
                ('b_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Main_accords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True)),
                ('accord', models.CharField(blank=True, max_length=200, null=True)),
                ('p_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('young', models.PositiveIntegerField(blank=True, null=True)),
                ('old', models.PositiveIntegerField(blank=True, null=True)),
                ('men', models.PositiveIntegerField(blank=True, null=True)),
                ('women', models.PositiveIntegerField(blank=True, null=True)),
                ('p_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.products')),
            ],
        ),
        migrations.CreateModel(
            name='All_fragnances_by_brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('b_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fragapp.brand')),
            ],
        ),
    ]
