# Generated by Django 3.2.8 on 2021-10-17 08:51

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('fragapp', '0002_auto_20211016_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_notes',
            name='base_note',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=0, max_length=66, size=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_notes',
            name='middle_note',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=0, max_length=66, size=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_notes',
            name='others',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=0, max_length=66, size=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_notes',
            name='top_note',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default=0, max_length=66, size=6),
            preserve_default=False,
        ),
    ]
