# Generated by Django 3.2.8 on 2021-10-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragapp', '0003_auto_20211017_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='about',
            new_name='about_brand',
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_understanding',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
