# Generated by Django 3.2.8 on 2021-10-18 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragapp', '0004_auto_20211018_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
