# Generated by Django 3.2.8 on 2021-10-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragapp', '0005_brand_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_understanding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
