# Generated by Django 3.2.8 on 2021-10-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragapp', '0006_alter_brand_brand_understanding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popular_products_by_brands',
            name='year',
        ),
        migrations.AlterField(
            model_name='most_used_notes_by_brand',
            name='accord',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
