# Generated by Django 3.2.8 on 2021-10-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragapp', '0008_alter_all_fragnances_by_brand_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='colour',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='reference',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
