# Generated by Django 3.2.8 on 2021-10-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragapp', '0009_auto_20211019_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasons',
            name='day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='fall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='night',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='spring',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='summer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='winter',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
