# Generated by Django 3.2.8 on 2021-10-19 11:31

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('fragapp', '0010_auto_20211019_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_notes',
            name='base_note',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='', max_length=66, size=6),
        ),
        migrations.AlterField(
            model_name='product_notes',
            name='middle_note',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='', max_length=66, size=6),
        ),
        migrations.AlterField(
            model_name='product_notes',
            name='others',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='', max_length=66, size=6),
        ),
        migrations.AlterField(
            model_name='product_notes',
            name='top_note',
            field=django_mysql.models.ListCharField(models.CharField(max_length=10), default='', max_length=66, size=6),
        ),
    ]
