# Generated by Django 3.2.8 on 2021-10-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fragapp', '0013_auto_20211019_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_notes',
            name='base_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_notes',
            name='middle_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_notes',
            name='others',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_notes',
            name='top_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
