from bulk_update_or_create import BulkUpdateOrCreateQuerySet

import bulk_update_or_create

from .models import *

from django.http import HttpResponse

from django_pandas.io import read_frame

import pandas as pd

def home(request):

	fragrantica_data = [{'Brand_Name': 'A Lab on Fire',
	  'Brand_Official_link': 'http://www.tizianaterenzi.com',
	  'Brands_Activity': 'Fragrances',
	  'Brands_Country': 'Italy',
	  'About_Brand': 'Tiziana Terenzi is a family owned Italian niche brand of fragrances, primarily scented candles and then perfumes. It was established as Cereria Terenzi in 1968 in Cattolica, in a space of 16 square meters, upon the enthusiasm of its founder, Evelino Terenzi, who, through innovation, continued a family tradition: his father, Guglielmo, participated in the foundation of a waxworks that produced devotional and Paschal candles for churches. With the help of his wife, Luigia Mancini, he set up an artisan laboratory in a small room of the big family home; the first brick in what would become a tale of over 40 years, passed down to the current day, generation by generation. Evelino Terenzi’s children, Tiziana and Paolo are now the owners of the brand. Tiziana Terenzi is the designer, while Paolo Terenzi is the nose and the president of company. Designer Tiziana Terenzi has 82 perfumes in our fragrance base. Tiziana Terenzi is a new fragrance brand. The earliest edition was created in 2012 and the newest is from 2021. Tiziana Terenzi fragrances were made in collaboration with perfumers Paolo Terenzi and Tiziana Terenzi.',
	  'Reference': 'https://www.fragrantica.com/designers/Tiziana-Terenzi.html',
	  'Image': 'https://fimgs.net/mdimg/dizajneri/o.1535.jpg'},
	 {'Brand_Name': 'Maison Francis Kurkdjian',
	  'Brand_Official_link': 'http://www.franciskurkdjian.com/',
	  'Brands_Activity': 'Fragrances',
	  'Brands_Country': 'France',
	  'About_Brand': 'Designer Maison Francis Kurkdjian has 52 perfumes in our fragrance base. Maison Francis Kurkdjian is a new fragrance brand. The earliest edition was created in 2009 and the newest is from 2021. The nose who worked on the fragrances is Francis Kurkdjian',
	  'Reference': 'https://www.fragrantica.com/designers/Maison-Francis-Kurkdjian.html',
	  'Image': 'https://fimgs.net/mdimg/dizajneri/o.770.jpg'},
	 {'Brand_Name': 'Burberry',
	  'Brand_Official_link': 'http://www.burberry.com/',
	  'Brands_Activity': 'Fashion',
	  'Brands_Country': 'United Kingdom',
	  'About_Brand': "Burberry is a luxury British design house founded by Thomas Burberry in 1856. This house distinguished itself with fashion and accessories, including a now-iconic trench coat and the brand's unique and recognizable tartan pattern which has become one of the most-copied motifs in fashion. Burberry was granted a Royal Warrant for Clothing from the British Royal Family. In addition to their fashion line and accessories, the Burberry brand offers an exclusive line of fragrances for men and women—many in bottles adorned with the company's signature tartan—under arrangement with Inter Parfums. Their first perfume, Burberry for Men, appeared in 1981. Designer Burberry has 83 perfumes in our fragrance base. The earliest edition was created in 1981 and the newest is from 2021. Burberry fragrances were made in collaboration with perfumers Creations Aromatiques, Michel Almairac, Philippe Roques, Mark Buxton, Emilie (Bevierre) Coppermann, Francis Kurkdjian, Dominique Ropion, Nathalie Gracia-Cetto, Antoine Maisondieu, Antoine Lie, Anne Flipo, Olivier Polge, Sonia Constant, Jerome Di Marino, Maïa Lernout, Aurelien Guichard, Jean-Marc Chaillan, Beatrice Piquet, Domitille Michalon Bertier, Michel Girard, Jean-Pierre Bethouart and Nathalie Lorson.",
	  'Reference': 'https://www.fragrantica.com/designers/Burberry.html',
	  'Image': 'https://fimgs.net/mdimg/dizajneri/o.104.jpg'},
	 {'Brand_Name': 'Mancera',
	  'Brand_Official_link': 'http://manceraparfums.com/',
	  'Brands_Activity': 'Fragrances',
	  'Brands_Country': 'France',
	  'About_Brand': 'Perfumer Pierre Mancera opened his first Mancera luxurious perfume boutique at Place Vendome in Paris. Mancera perfumes are made from precious and luxurious ingredients, rare and refined materials, inspired by Art Deco design. Designer Mancera has 76 perfumes in our fragrance base. Mancera is a new fragrance brand. The earliest edition was created in 2008 and the newest is from 2021. The nose who worked on the fragrances is Pierre Montale',
	  'Reference': 'https://www.fragrantica.com/designers/Mancera.html',
	  'Image': 'https://fimgs.net/mdimg/dizajneri/o.1134.jpg'}]

	frag_df = pd.DataFrame(fragrantica_data)

	perfuma_data = [{'Brand_Name': 'A Lab on Fire',
	  'Brand_Official_link': 'http://www.alabonfire.com/',
	  'Brands_Country': 'USA',
	  'Brand_Understanding': 'Founded by Raymond Cloosterman in 2000, Ritual...',
	  'Rating': 'Perfumes of this brand have been rated 7.3 of 10 on average. out of 952 perfume ratings.',
	  'Reference': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire'},
	 {'Brand_Name': 'Aedes de Venustas',
	  'Brand_Official_link': 'http://www.aedes.com',
	  'Brands_Country': 'USA',
	  'Brand_Understanding': 'Founded by Raymond Cloosterman in 2000, Ritual...',
	  'Rating': 'Perfumes of this brand have been rated 7.8 of 10 on average. out of 1324 perfume ratings.',
	  'Reference': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas'},
	 {'Brand_Name': 'Tuttotondo',
	  'Brand_Official_link': 'http://www.tutto-tondo.com/',
	  'Brands_Country': 'Italy',
	  'Brand_Understanding': 'Founded by Raymond Cloosterman in 2000, Ritual...',
	  'Rating': 'Perfumes of this brand have been rated 7.4 of 10 on average. out of 305 perfume ratings.',
	  'Reference': 'https://www.parfumo.net/Perfumes/Tuttotondo'},
	 {'Brand_Name': 'Rituals',
	  'Brand_Official_link': 'https://www.rituals.com',
	  'Brands_Country': 'Netherlands',
	  'Brand_Understanding': 'Founded by Raymond Cloosterman in 2000, Rituals Cosmetics is headquartered in Amsterdam and has over 800 stores worldwide.\n\nIts portfolio includes body and facial care lines, as well as products for the olfactory optimization of the living space.\n\nIn terms of product concept, Rituals draws on ancient Far Eastern traditions and combines carefully selected ingredients with modern manufacturing processes. According to the company, natural, renewable raw materials as well as harmless base materials are to be used. The company is explicitly in favor of animal welfare and supports the Dutch Association to Combat Animal Testing.',
	  'Rating': 'Perfumes of this brand have been rated 7.4 of 10 on average. out of 2307 perfume ratings.',
	  'Reference': 'https://www.parfumo.net/Perfumes/Rituals'}]

	perfuma_df = pd.DataFrame(perfuma_data)

	common_df = frag_df.merge(perfuma_df[['Brand_Name','Brand_Understanding','Rating']])

	concat_df = pd.concat([frag_df,perfuma_df]).drop_duplicates(subset=['Brand_Name'],keep=False)
	new_concat_df = pd.concat([concat_df,common_df])

	#BUG - HARDCODING
	# df = frag_df['Brand_Name'] != perfuma_df['Brand_Name']

	# concat_df = pd.concat([frag_df[df],perfuma_df[df]],axis=0)

	# concat_df_common = pd.concat([concat_df,common_df],axis=0)

	# Drop=true
	new_concat_df.reset_index(inplace=True) #
	new_concat_df.drop(columns=['index'])

	transpose_data = new_concat_df.fillna('Not Found').transpose()

	final_brand_data = transpose_data.to_dict()

	# print(final_brand_data)


	# print(final_brand_data)

	brand_instances = [Brand(

		b_name=value['Brand_Name'],
		official_link=value['Brand_Official_link'],
		activity=value['Brands_Activity'],
		about_brand=value['About_Brand'],
		country=value['Brands_Country'],
		rating = value['Rating'],
		reference = value['Reference'],
		brand_understanding = value['Brand_Understanding'],
		image = value['Image']

		) for key,value in final_brand_data.items()]
	Brand.objects.bulk_update_or_create(brand_instances,['b_name','official_link','activity','about_brand','country','rating','reference','brand_understanding','image'],match_field=['b_name','official_link','activity','about_brand','country','rating','reference','brand_understanding','image'])

	getBrandData = Brand.objects.values('id','b_name')
	brand_dataframe = read_frame(getBrandData)



	product = [{'Name': 'Messy Sexy Just Rolled Out Of Bed',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/79531_2nuhe5_messy_sexy_just_rolled_out_of_bed_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/Messy_Sexy_Just_Rolled_Out_Of_Bed',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'Liquidnight',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/21534_img-3772-a_lab_on_fire-liquidnight_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/Liquidnight',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'Almost Transparent Blue',
	  'Sex': 'Male',
	  'Image': 'https://pimages.parfumo.de/240/26737_img-4925-a-lab-on-fire-almost-transparent-blue_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/Almost_Transparent_Blue',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'What We Do In Paris Is Secret',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/15123_7dk334ghp7_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/What_We_Do_In_Paris_Is_Secret',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'ParisL A ',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/47443_u2m3nx_parisl_a__240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/ParisL_A_',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'California Snow',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/94795_img-9214-a_lab_on_fire-california_snow_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/California_Snow',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'Hossegor',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/115798_img-1021-a_lab_on_fire-hossegor_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/Hossegor',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'Hallucinogenic Pearl',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/104707_img-3677-a_lab_on_fire-hallucinogenic_pearl_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/Hallucinogenic_Pearl',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'Rose Rebelle Respawn',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/25233_zauh6tpdok_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/Rose_Rebelle_Respawn',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'My Own Private Teahupo o',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/87680_img-5548-a-lab-on-fire-my-own-private-teahupo-o_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/My_Own_Private_Teahupo_o',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'Sweet Dreams 2003',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/19220_dqzn4mpvxm_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/Sweet_Dreams_2003',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'L Anonyme ou OP1475A',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/12315_img-3248-a_lab_on_fire-l_anonyme_ou_op_1475_a_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/L_Anonyme_ou_OP1475A',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'Made in Heaven',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/47444_dqsfih_made_in_heaven_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/Made_in_Heaven',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'Eau d Ipanema',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/72611_zn22pq_eau_d_ipanema_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/Eau_d_Ipanema',
	  'Brand': 'A Lab on Fire'},
	 {'Name': 'Cierge de Lune',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/71665_c23xfq_cierge_de_lune_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Cierge_de_Lune',
	  'Brand': 'Aedes de Venustas'},
	 {'Name': 'Copal Azur',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/51694_img-1643-aedes_de_venustas-copal_azur_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Copal_Azur',
	  'Brand': 'Aedes de Venustas'},
	 {'Name': 'Iris Nazarena',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/27341_img-8019-aedes_de_venustas-iris_nazarena_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Iris_Nazarena',
	  'Brand': 'Aedes de Venustas'},
	 {'Name': 'Oeillet Bengale',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/43685_7h2juu_oeillet_bengale_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Oeillet_Bengale',
	  'Brand': 'Aedes de Venustas'},
	 {'Name': 'Palissandre d Or',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/56993_img-5288-aedes-de-venustas-palissandre-d-or_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Palissandre_d_Or',
	  'Brand': 'Aedes de Venustas'},
	 {'Name': 'Pelargonium',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/87701_o7tnc4_pelargonium_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Pelargonium',
	  'Brand': 'Aedes de Venustas'},
	 {'Name': 'Grenadille d Afrique',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/78821_88uowm_grenadille_d_afrique_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Grenadille_d_Afrique',
	  'Brand': 'Aedes de Venustas'},
	 {'Name': 'Aedes de Venustas',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/18110_img-5275-aedes-de-venustas-aedes-de-venustas_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Aedes_de_Venustas',
	  'Brand': 'Aedes de Venustas'},
	 {'Name': 'Musc Encense',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/108007_img-2951-aedes_de_venustas-musc_encense_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Musc_Encense',
	  'Brand': 'Aedes de Venustas'},
	 {'Name': 'Fico d India',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/73255_784mno_fico_d_india_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Fico_d_India',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Erbe Alpine',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/73254_img-2267-tuttotondo-erbe_alpine_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Erbe_Alpine',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Riso',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/87086_img-9805-tuttotondo-riso_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Riso',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Mirto',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/73252_vi0qu4_mirto_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Mirto',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Chinotto',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/73253_img-2395-tuttotondo-chinotto_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Chinotto',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Pan d Oro',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/80885_hoyag7_pan_d_oro_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Pan_d_Oro',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Castagna',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/73256_72x34k_castagna_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Castagna',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Vela',
	  'Sex': 'Male',
	  'Image': 'https://pimages.parfumo.de/240/110383_img-9964-tuttotondo-vela_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Vela',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Scherma',
	  'Sex': 'Male',
	  'Image': 'https://pimages.parfumo.de/240/97295_img-5518-tuttotondo-scherma_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Scherma',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'spritz veneziano',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/138285_img-5568-tuttotondo-spritz-veneziano_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/spritz-veneziano',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Golf',
	  'Sex': 'Male',
	  'Image': 'https://pimages.parfumo.de/240/97296_img-4443-tuttotondo-golf_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/Golf',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'tiramisu',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/154420_img-4665-tuttotondo-tiramisu_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Tuttotondo/tiramisu',
	  'Brand': 'Tuttotondo'},
	 {'Name': 'Oriental Essences  Roi d Orient',
	  'Sex': 'Male',
	  'Image': 'https://pimages.parfumo.de/240/65021_img-8750-rituals-oriental-essence-roi-d-orient_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essences__Roi_d_Orient',
	  'Brand': 'Rituals'},
	 {'Name': 'Oriental Essences  Elixir d Orient Eau d Orient',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/64079_fiibza_oriental_essences__elixir_d_orient_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essences__Elixir_d_Orient_Eau_d_Orient',
	  'Brand': 'Rituals'},
	 {'Name': 'The Ritual of Karma',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/74938_8au2ng_the_ritual_of_karma_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/The_Ritual_of_Karma',
	  'Brand': 'Rituals'},
	 {'Name': 'Oriental Essence  Victoire d Ambre',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/96579_img-8768-rituals-oriental_essence__victoire_d_ambre_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essence__Victoire_d_Ambre',
	  'Brand': 'Rituals'},
	 {'Name': 'The Ritual of Dao Yin  Organic White Lotus  Yi Yi Ren',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/11487_r8updp_the_ritual_of_dao_yin__organic_white_lotus__yi_yi_ren_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/The_Ritual_of_Dao_Yin__Organic_White_Lotus__Yi_Yi_Ren',
	  'Brand': 'Rituals'},
	 {'Name': 'Oriental Essences  Voyage en Inde',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/79458_vtzhau_oriental_essences__voyage_en_inde_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essences__Voyage_en_Inde',
	  'Brand': 'Rituals'},
	 {'Name': 'Oriental Essences  Fleurs de L Himalaya',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/65015_img-6675-rituals-oriental_essence__fleurs_de_l_himalaya_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essences__Fleurs_de_L_Himalaya',
	  'Brand': 'Rituals'},
	 {'Name': 'Oriental Essence  Nuit d Azar',
	  'Sex': 'Male',
	  'Image': 'https://pimages.parfumo.de/240/117010_img-3827-rituals-oriental_essence__nuit_d_azar_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essence__Nuit_d_Azar',
	  'Brand': 'Rituals'},
	 {'Name': 'Oriental Essence  Oasis de Fleurs',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/86021_img-1430-rituals-oriental_essence__oasis_de_fleurs_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essence__Oasis_de_Fleurs',
	  'Brand': 'Rituals'},
	 {'Name': 'Oriental Essence  Oasis Verte',
	  'Sex': 'Male',
	  'Image': 'https://pimages.parfumo.de/240/86020_img-5437-rituals-oriental-essence-oasis-verte_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essence__Oasis_Verte',
	  'Brand': 'Rituals'},
	 {'Name': 'oriental essence rose de shiraz',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/133830_img-1458-rituals-oriental-essence-rose-de-shiraz_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/oriental-essence-rose-de-shiraz',
	  'Brand': 'Rituals'},
	 {'Name': 'The Ritual of Sakura Blossom Water  Cherry Blossom',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/11488_5qi0pj_the_ritual_of_sakura_blossom_water__cherry_blossom_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/The_Ritual_of_Sakura_Blossom_Water__Cherry_Blossom',
	  'Brand': 'Rituals'},
	 {'Name': 'Oriental Essences  Nuit  Marrakech',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/65016_gfu006_oriental_essences__nuit__marrakech_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essences__Nuit__Marrakech',
	  'Brand': 'Rituals'},
	{'Name': 'Oriental Essences  Nuit  Marrakech',
	  'Sex': 'Female',
	  'Image': 'https://pimages.parfumo.de/240/65016_gfu006_oriental_essences__nuit__marrakech_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essences__Nuit__Marrakech',
	  'Brand': 'Koi bhi'},
	 {'Name': 'The Ritual of Ayurveda Chakra Water  Indian Rose  Himalaya Honey',
	  'Sex': 'Unisex',
	  'Image': 'https://pimages.parfumo.de/240/43526_kix2o3_chakra_water_indian_rose__himalaya_honey_240.webp',
	  'link': 'https://www.parfumo.net/Perfumes/Rituals/The_Ritual_of_Ayurveda_Chakra_Water__Indian_Rose__Himalaya_Honey',
	  'Brand': 'Rituals'}]

	product_df = pd.DataFrame(product)

	df_join = pd.merge(brand_dataframe, product_df, how="left", left_on='b_name',right_on='Brand').dropna().sort_values(['id'])

	transpose_product = df_join.transpose()
	final_product_data = transpose_product.to_dict()


	product_instances = [Popular_products_by_brands(

		b_name_id=value['id'],
		p_name=value['Name'],
		link=value['link'],
		sex=value['Sex'],
		image=value['Image']

		) for key,value in final_product_data.items()]
	Popular_products_by_brands.objects.bulk_update_or_create(product_instances,['b_name_id','p_name','link','sex','image'],match_field=['b_name_id','p_name','link','sex','image'])


	most_used_notes_by_brands = [{'Accord': 'Musk', 'Score': '14', 'Brand': 'A Lab on Fire'},
	 {'Accord': 'Bergamot', 'Score': '10', 'Brand': 'A Lab on Fire'},
	 {'Accord': 'Vanilla', 'Score': '7', 'Brand': 'A Lab on Fire'},
	 {'Accord': 'Sandalwood', 'Score': '6', 'Brand': 'A Lab on Fire'},
	 {'Accord': 'Heliotrope', 'Score': '5', 'Brand': 'A Lab on Fire'},
	 {'Accord': 'Turkish rose', 'Score': '5', 'Brand': 'A Lab on Fire'},
	 {'Accord': 'Amber', 'Score': '4', 'Brand': 'A Lab on Fire'},
	 {'Accord': 'Jasmine', 'Score': '4', 'Brand': 'A Lab on Fire'},
	 {'Accord': 'Frankincense', 'Score': '7', 'Brand': 'Aedes de Venustas'},
	 {'Accord': 'Musk', 'Score': '4', 'Brand': 'Aedes de Venustas'},
	 {'Accord': 'Vetiver', 'Score': '4', 'Brand': 'Aedes de Venustas'},
	 {'Accord': 'Cardamom', 'Score': '3', 'Brand': 'Aedes de Venustas'},
	 {'Accord': 'Black pepper', 'Score': '3', 'Brand': 'Aedes de Venustas'},
	 {'Accord': 'Bergamot', 'Score': '3', 'Brand': 'Aedes de Venustas'},
	 {'Accord': 'Patchouli', 'Score': '3', 'Brand': 'Aedes de Venustas'},
	 {'Accord': 'Clary sage', 'Score': '2', 'Brand': 'Aedes de Venustas'},
	 {'Accord': 'Musk', 'Score': '7', 'Brand': 'Tuttotondo'},
	 {'Accord': 'Vanilla', 'Score': '4', 'Brand': 'Tuttotondo'},
	 {'Accord': 'Bergamot', 'Score': '4', 'Brand': 'Tuttotondo'},
	 {'Accord': 'Amber', 'Score': '4', 'Brand': 'Tuttotondo'},
	 {'Accord': 'Iris', 'Score': '3', 'Brand': 'Tuttotondo'},
	 {'Accord': 'Nutmeg', 'Score': '3', 'Brand': 'Tuttotondo'},
	 {'Accord': 'Orange', 'Score': '3', 'Brand': 'Tuttotondo'},
	 {'Accord': 'Vetiver', 'Score': '2', 'Brand': 'Tuttotondo'},
	 {'Accord': 'Patchouli', 'Score': '16', 'Brand': 'Rituals'},
	 {'Accord': 'Bergamot', 'Score': '13', 'Brand': 'Rituals'},
	 {'Accord': 'Musk', 'Score': '9', 'Brand': 'Rituals'},
	 {'Accord': 'Mandarin orange', 'Score': '7', 'Brand': 'Rituals'},
	 {'Accord': 'Amber', 'Score': '6', 'Brand': 'Rituals'},
	 {'Accord': 'Sandalwood', 'Score': '6', 'Brand': 'Rituals'},
	 {'Accord': 'Cedarwood', 'Score': '5', 'Brand': 'Rituals'},
	 {'Accord': 'Cedarwood', 'Score': '5', 'Brand': 'koi bhi'},
	 {'Accord': 'Pear', 'Score': '5', 'Brand': 'Rituals'}]


	getNotesdf = pd.DataFrame(most_used_notes_by_brands)

	brand_df_join_notes_df = pd.merge(brand_dataframe,getNotesdf,how='left',left_on='b_name',right_on='Brand').dropna().sort_values(['id'])
	brand_df_join_notes_df['Score'] = brand_df_join_notes_df['Score'].astype(int)
	transpose_notes = brand_df_join_notes_df.transpose()
	getfinalNotes = transpose_notes.to_dict()

	notes_instances = [Most_used_notes_by_brand(

		b_name_id = value['id'],
		score = value['Score'],
		accord = value['Accord']

		) for key,value in getfinalNotes.items()]

	Most_used_notes_by_brand.objects.bulk_update_or_create(notes_instances,['b_name_id','score','accord'],match_field=['b_name_id','score','accord'])

	fragnances = [{'Name': 'A Blvd Called Sunset',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/A-Blvd-Called-Sunset-63373.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.63373.jpg',
	  'Year': '2020',
	  'Sex': 'male',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Almost Transparent Blue',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Almost-Transparent-Blue-18847.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.18847.jpg',
	  'Year': '2013',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'And The World Is Yours',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/And-The-World-Is-Yours-48814.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.48814.jpg',
	  'Year': '2018',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'California Snow',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/California-Snow-46590.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.46590.jpg',
	  'Year': '2017',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Eau d Ipanema',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Eau-d-Ipanema-37786.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.37786.jpg',
	  'Year': '2016',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Freckled and Beautiful',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Freckled-and-Beautiful-62035.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.62035.jpg',
	  'Year': '2020',
	  'Sex': 'female',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Hallucinogenic Pearl',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Hallucinogenic-Pearl-48820.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.48820.jpg',
	  'Year': '2018',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Hossegor',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Hossegor-51574.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.51574.jpg',
	  'Year': '2018',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'L Anonyme ou OP 1475 A',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/L-Anonyme-ou-OP-1475-A-11920.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.11920.jpg',
	  'Year': '2011',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Liquidnight',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Liquidnight-16919.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.16919.jpg',
	  'Year': '2012',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Made in Heaven',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Made-in-Heaven-27620.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.27620.jpg',
	  'Year': '2014',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Messy Sexy Just Rolled out of Bed',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Messy-Sexy-Just-Rolled-out-of-Bed-40574.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.40574.jpg',
	  'Year': '2016',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'My Own Private Teahupo o',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/My-Own-Private-Teahupo-o-44586.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.44586.jpg',
	  'Year': '2017',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Oxymusc',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Oxymusc-26146.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.26146.jpg',
	  'Year': '2014',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Paris L A',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Paris-L-A-27619.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.27619.jpg',
	  'Year': '2014',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Rose Rebelle',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Rose-Rebelle-17441.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.17441.jpg',
	  'Year': '2011',
	  'Sex': 'female',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Rose Rebelle Respawn',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Rose-Rebelle-Respawn-17855.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.17855.jpg',
	  'Year': '2013',
	  'Sex': 'female',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Sweet Dreams 2003',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Sweet-Dreams-2003-14390.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.14390.jpg',
	  'Year': '2012',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'What We Do In Paris Is Secret',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/What-We-Do-In-Paris-Is-Secret-14389.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.14389.jpg',
	  'Year': '2012',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Monoscent E',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Monoscent-E-57372.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.57372.jpg',
	  'Year': '2019',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Monoscent G',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Monoscent-G-57371.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.57371.jpg',
	  'Year': '2019',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Mon Musc a Moi',
	  'Link': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/Mon-Musc-a-Moi-32468.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.32468.jpg',
	  'Year': '2015',
	  'Sex': 'unisex',
	  'Brand_Name': 'A Lab on Fire'},
	 {'Name': 'Bleu Byzantin',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Bleu-Byzantin-33203.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.33203.jpg',
	  'Year': '2015',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Eau des Indes',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Eau-des-Indes-33124.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.33124.jpg',
	  'Year': '2015',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Eau du Kashmir',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Eau-du-Kashmir-33200.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.33200.jpg',
	  'Year': '2015',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Elixir d Orient',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Elixir-d-Orient-33123.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.33123.jpg',
	  'Year': '2015',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Fleurs de L Himalaya',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Fleurs-de-L-Himalaya-33199.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.33199.jpg',
	  'Year': '2015',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'L Essence',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/L-Essence-58099.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.58099.jpg',
	  'Year': '2019',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 01 Ginger Essence White Tea',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-01-Ginger-Essence-White-Tea-10987.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.10987.jpg',
	  'Year': '2010',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 04 Violet White Lily',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-04-Violet-White-Lily-10988.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.10988.jpg',
	  'Year': '2010',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 06 Green Bergamot Vetiver',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-06-Green-Bergamot-Vetiver-10992.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.10992.jpg',
	  'Year': '2010',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 07 White Patchouli Cedarwood',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-07-White-Patchouli-Cedarwood-10989.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.10989.jpg',
	  'Year': '2010',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 09 Vanilla Sweet Orange Drops',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-09-Vanilla-Sweet-Orange-Drops-10990.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.10990.jpg',
	  'Year': '2010',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 10 Lemongrass Neroli',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-10-Lemongrass-Neroli-19198.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.19198.jpg',
	  'Year': 'Unkown',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 14 Cypress Fresh Tangerine',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-14-Cypress-Fresh-Tangerine-10993.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.10993.jpg',
	  'Year': '2010',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 17 Vetiver Bergamot',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-17-Vetiver-Bergamot-18840.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.18840.jpg',
	  'Year': '2013',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 18 Sandal Wood Wild Rose',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-18-Sandal-Wood-Wild-Rose-10991.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.10991.jpg',
	  'Year': '2010',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 19 Sandal Wood Patchouli',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-19-Sandal-Wood-Patchouli-10994.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.10994.jpg',
	  'Year': '2010',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'No 23 Magnolia Pink Pepper',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/No-23-Magnolia-Pink-Pepper-18839.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.18839.jpg',
	  'Year': '2013',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Nuit a Marrakech',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Nuit-a-Marrakech-33126.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.33126.jpg',
	  'Year': '2015',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Reve de Hanami',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Reve-de-Hanami-68368.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.68368.jpg',
	  'Year': '2021',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Roi d Orient',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Roi-d-Orient-33201.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.33201.jpg',
	  'Year': '2015',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Sultan de Muscat',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Sultan-de-Muscat-33202.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.33202.jpg',
	  'Year': '2015',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Oasis de Fleurs',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Oasis-de-Fleurs-43867.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.43867.jpg',
	  'Year': '2017',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Oasis Verte',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Oasis-Verte-43868.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.43868.jpg',
	  'Year': '2017',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'L Eclat',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/L-Eclat-63639.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.63639.jpg',
	  'Year': '2020',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Maharaja d Or',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Maharaja-d-Or-41952.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.41952.jpg',
	  'Year': '2016',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Ocean Indigo',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Ocean-Indigo-50868.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.50868.jpg',
	  'Year': '2018',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Ocean Infini',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Ocean-Infini-50867.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.50867.jpg',
	  'Year': '2018',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Palace d Ambre',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Palace-d-Ambre-47601.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.47601.jpg',
	  'Year': '2017',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Rose de Shiraz',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Rose-de-Shiraz-58782.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.58782.jpg',
	  'Year': '2019',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Soleil d Or',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Soleil-d-Or-69306.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.69306.jpg',
	  'Year': '2021',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Victoire d Ambre',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Victoire-d-Ambre-47600.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.47600.jpg',
	  'Year': '2017',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Voyage en Inde',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Voyage-en-Inde-41951.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.41951.jpg',
	  'Year': '2016',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Amsterdam Collection',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Amsterdam-Collection-56764.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.56764.jpg',
	  'Year': '2019',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Ritual of Holi Spring Love',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Ritual-of-Holi-Spring-Love-61330.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.61330.jpg',
	  'Year': '2020',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Ritual of Holi Sugar Love',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Ritual-of-Holi-Sugar-Love-52640.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.52640.jpg',
	  'Year': '2018',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Ritual of Karma',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Ritual-of-Karma-46391.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.46391.jpg',
	  'Year': 'Unkown',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Rituals of Ayurveda',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Rituals-of-Ayurveda-52638.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.52638.jpg',
	  'Year': 'Unkown',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Rituals of Dao',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Rituals-of-Dao-52636.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.52636.jpg',
	  'Year': 'Unkown',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Rituals of Hammam',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Rituals-of-Hammam-52639.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.52639.jpg',
	  'Year': 'Unkown',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Rituals of Happy Buddha',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Rituals-of-Happy-Buddha-52637.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.52637.jpg',
	  'Year': 'Unkown',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Rituals of Sakura',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Rituals-of-Sakura-52635.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.52635.jpg',
	  'Year': 'Unkown',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'The Ritual of Chado',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/The-Ritual-of-Chado-54804.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.54804.jpg',
	  'Year': '2019',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'The Ritual of Jing',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/The-Ritual-of-Jing-60001.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.60001.jpg',
	  'Year': '2020',
	  'Sex': 'unisex',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Serendipity For Her',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Serendipity-For-Her-69867.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.69867.jpg',
	  'Year': '2021',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Serendipity For Him',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Serendipity-For-Him-69868.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.69868.jpg',
	  'Year': '2021',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Chabana',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Chabana-54802.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.54802.jpg',
	  'Year': '2019',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Chakai',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Chakai-54803.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.54803.jpg',
	  'Year': '2019',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Eau My Gosh',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Eau-My-Gosh-61333.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.61333.jpg',
	  'Year': '2020',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Eau So Lovely',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Eau-So-Lovely-61331.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.61331.jpg',
	  'Year': '2020',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Eau So Sunny',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Eau-So-Sunny-61332.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.61332.jpg',
	  'Year': '2020',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Oudh Pour Femme',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Oudh-Pour-Femme-69737.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.69737.jpg',
	  'Year': '2019',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Oudh Pour Homme',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Oudh-Pour-Homme-69738.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.69738.jpg',
	  'Year': '2019',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Eau de Tsuru',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Eau-de-Tsuru-57973.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.57973.jpg',
	  'Year': '2019',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Fuyu D Or',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Fuyu-D-Or-57972.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.57972.jpg',
	  'Year': '2019',
	  'Sex': 'female',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Nuit d Azar',
	  'Link': 'https://www.fragrantica.com/perfume/Rituals/Nuit-d-Azar-52028.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.52028.jpg',
	  'Year': '2018',
	  'Sex': 'male',
	  'Brand_Name': 'Rituals'},
	 {'Name': 'Castagna',
	  'Link': 'https://www.fragrantica.com/perfume/Tuttotondo/Castagna-41148.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.41148.jpg',
	  'Year': '2016',
	  'Sex': 'unisex',
	  'Brand_Name': 'Tuttotondo'},
	 {'Name': 'Chinotto',
	  'Link': 'https://www.fragrantica.com/perfume/Tuttotondo/Chinotto-41144.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.41144.jpg',
	  'Year': '2016',
	  'Sex': 'unisex',
	  'Brand_Name': 'Tuttotondo'},
	 {'Name': 'Erbe Alpine',
	  'Link': 'https://www.fragrantica.com/perfume/Tuttotondo/Erbe-Alpine-41146.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.41146.jpg',
	  'Year': '2016',
	  'Sex': 'unisex',
	  'Brand_Name': 'Tuttotondo'},
	 {'Name': 'Fico d India',
	  'Link': 'https://www.fragrantica.com/perfume/Tuttotondo/Fico-d-India-41147.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.41147.jpg',
	  'Year': '2016',
	  'Sex': 'unisex',
	  'Brand_Name': 'Tuttotondo'},
	 {'Name': 'Golf',
	  'Link': 'https://www.fragrantica.com/perfume/Tuttotondo/Golf-47141.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.47141.jpg',
	  'Year': '2017',
	  'Sex': 'unisex',
	  'Brand_Name': 'Tuttotondo'},
	 {'Name': 'Mirto',
	  'Link': 'https://www.fragrantica.com/perfume/Tuttotondo/Mirto-41145.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.41145.jpg',
	  'Year': '2016',
	  'Sex': 'unisex',
	  'Brand_Name': 'Tuttotondo'},
	 {'Name': 'Scherma',
	  'Link': 'https://www.fragrantica.com/perfume/Tuttotondo/Scherma-47140.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.47140.jpg',
	  'Year': '2017',
	  'Sex': 'unisex',
	  'Brand_Name': 'Tuttotondo'},
	 {'Name': 'Spritz Veneziano',
	  'Link': 'https://www.fragrantica.com/perfume/Tuttotondo/Spritz-Veneziano-60136.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.60136.jpg',
	  'Year': '2020',
	  'Sex': 'unisex',
	  'Brand_Name': 'Tuttotondo'},
	 {'Name': 'Aedes de Venustas Eau de Parfum',
	  'Link': 'https://www.fragrantica.com/perfume/Aedes-de-Venustas/Aedes-de-Venustas-Eau-de-Parfum-14890.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.14890.jpg',
	  'Year': '2012',
	  'Sex': 'female',
	  'Brand_Name': 'Aedes de Venustas'},
	 {'Name': 'Cierge De Lune',
	  'Link': 'https://www.fragrantica.com/perfume/Aedes-de-Venustas/Cierge-De-Lune-36828.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.36828.jpg',
	  'Year': '2016',
	  'Sex': 'unisex',
	  'Brand_Name': 'Aedes de Venustas'},
	 {'Name': 'Copal Azur',
	  'Link': 'https://www.fragrantica.com/perfume/Aedes-de-Venustas/Copal-Azur-28157.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.28157.jpg',
	  'Year': '2014',
	  'Sex': 'unisex',
	  'Brand_Name': 'Aedes de Venustas'},
	 {'Name': 'Grenadille d Afrique',
	  'Link': 'https://www.fragrantica.com/perfume/Aedes-de-Venustas/Grenadille-d-Afrique-40875.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.40875.jpg',
	  'Year': '2016',
	  'Sex': 'unisex',
	  'Brand_Name': 'Aedes de Venustas'},
	 {'Name': 'Iris Nazarena',
	  'Link': 'https://www.fragrantica.com/perfume/Aedes-de-Venustas/Iris-Nazarena-18451.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.18451.jpg',
	  'Year': '2013',
	  'Sex': 'unisex',
	  'Brand_Name': 'Aedes de Venustas'},
	 {'Name': 'Musc Encense',
	  'Link': 'https://www.fragrantica.com/perfume/Aedes-de-Venustas/Musc-Encense-49367.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.49367.jpg',
	  'Year': '2018',
	  'Sex': 'unisex',
	  'Brand_Name': 'Aedes de Venustas'},
	 {'Name': 'Oeillet Bengale',
	  'Link': 'https://www.fragrantica.com/perfume/Aedes-de-Venustas/Oeillet-Bengale-25467.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.25467.jpg',
	  'Year': '2014',
	  'Sex': 'unisex',
	  'Brand_Name': 'Aedes de Venustas'},
	 {'Name': 'Palissandre d Or',
	  'Link': 'https://www.fragrantica.com/perfume/Aedes-de-Venustas/Palissandre-d-Or-29945.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/m.29945.jpg',
	  'Year': '2015',
	  'Sex': 'unisex',
	  'Brand_Name': 'Aedes de Venustas'}]

	fragnances_df = pd.DataFrame(fragnances)
	join_fragnance_and_brand = pd.merge(brand_dataframe,fragnances_df,how='left',left_on='b_name',right_on='Brand_Name').dropna().sort_values(['id'])

	transpose_fragnance = join_fragnance_and_brand.transpose()
	getfragnanceData = transpose_fragnance.to_dict()

	print(getfragnanceData)

	fragnances_instance = [All_fragnances_by_brand(

		b_name_id = value['id'],
		name = value['Name'],
		link = value['Link'],
		image = value['Image'],
		year = value['Year'],
		sex = value['Sex']

		) for key,value in getfragnanceData.items()]

	All_fragnances_by_brand.objects.bulk_update_or_create(fragnances_instance,['b_name_id','name','link','image','year','sex'],match_field=['b_name_id','name','link','image','year','sex'])

	getBrandData = Brand.objects.values('id','b_name')

	perfuma_DF = [{'Brand_Name': 'Rituals',
	  'Product_Name': "Oriental Essence - Roi d'Orient",
	  'Product_Image': 'https://pimages.parfumo.de/480/65021_img-8750-rituals-oriental-essence-roi-d-orient_480.jpg',
	  'Time': '16:07:03 18/10/2021',
	  'Sex': 'Male',
	  'Year': '2015',
	  'Description': "Oriental Essence - Roi d'Orient is a popular perfume by Rituals for men and was released in 2015. The scent is spicy-oriental. It is still available",
	  'Reference': 'https://www.parfumo.net/Perfumes/Rituals/Oriental_Essences__Roi_d_Orient',
	  'Color': (203, 193, 177)},
	 {'Brand_Name': 'A Lab on Fire',
	  'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Product_Image': 'https://pimages.parfumo.de/480/12315_img-3248-a_lab_on_fire-l_anonyme_ou_op_1475_a_480.jpg',
	  'Time': '16:07:08 18/10/2021',
	  'Sex': 'Unisex',
	  'Year': '2011',
	  'Description': "L'Anonyme ou OP-1475-A is a perfume by A Lab on Fire for women and men and was released in 2011. The scent is floral-fresh. It is still available to purchase.",
	  'Reference': 'https://www.parfumo.net/Perfumes/A_Lab_on_Fire/L_Anonyme_ou_OP1475A',
	  'Color': (174, 174, 173)},
	 {'Brand_Name': 'Tuttotondo',
	  'Product_Name': "Fico d'India",
	  'Product_Image': 'https://pimages.parfumo.de/240/73255_784mno_fico_d_india_240.jpg',
	  'Time': '16:07:12 18/10/2021',
	  'Sex': 'Unisex',
	  'Year': '2016',
	  'Description': "Fico d'India is a popular perfume by Tuttotondo for women and men and was released in 2016. The scent is fruity-sweet. It is being marketed b",
	  'Reference': 'https://www.parfumo.net/Perfumes/Tuttotondo/Fico_d_India',
	  'Color': (141, 171, 166)},
	 {'Brand_Name': 'Aedes de Venustas',
	  'Product_Name': 'Iris Nazarena',
	  'Product_Image': 'https://pimages.parfumo.de/480/27341_img-8019-aedes_de_venustas-iris_nazarena_480.jpg',
	  'Time': '16:07:18 18/10/2021',
	  'Sex': 'Unisex',
	  'Year': '2013',
	  'Description': 'Iris Nazarena is a popular perfume by Aedes de Venustas for women and men and was released in 2013. The scent is powdery-woody. It is still available to purchase.',
	  'Reference': 'https://www.parfumo.net/Perfumes/Aedes_de_Venustas/Iris_Nazarena',
	  'Color': (136, 137, 125)}]

	read_perfuma_df = pd.DataFrame(perfuma_DF)

	fragrantica_DF = [{'Brand_Name': 'A Lab on Fire',
	  'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Product_Image': 'https://fimgs.net/mdimg/perfume/375x500.11920.jpg',
	  'Sex': 'Unisex',
	  'Time': '17:03:33 18/10/2021',
	  'Year': '2011',
	  'Description': "L'Anonyme ou OP-1475-A by A Lab on Fire is a Woody Aromatic fragrance for women and men. L'Anonyme ou OP-1475-A was launched in 2011. The nose behind this fragrance is Olivier Polge. Top note is Bergamot; middle note is Geranium; base notes are Woodsy Notes, Suede and Amber.",
	  'Reference': 'https://www.fragrantica.com/perfume/A-Lab-on-Fire/L-Anonyme-ou-OP-1475-A-11920.html',
	  'Color': (165, 166, 170)},
	 {'Brand_Name': 'Burberry',
	  'Product_Name': 'Burberry Her',
	  'Product_Image': 'https://fimgs.net/mdimg/perfume/375x500.51694.jpg',
	  'Sex': 'Female',
	  'Time': '17:03:45 18/10/2021',
	  'Year': '2018',
	  'Description': 'Burberry Her by Burberry is a Floral Fruity Gourmand fragrance for women. This is a new fragrance. Burberry Her was launched in 2018. The nose behind this fragrance is Francis Kurkdjian. Top notes are Strawberry, Raspberry, Blackberry, Sour Cherry, Black Currant, Mandarin Orange and Lemon; middle notes are Violet and Jasmine; base notes are Musk, Vanilla, Oakmoss, Cashmeran, Woody Notes, Amber and Patchouli.',
	  'Reference': 'https://www.fragrantica.com/perfume/Burberry/Burberry-Her-51694.html',
	  'Color': (239, 231, 228)},
	 {'Brand_Name': 'Maison Francis Kurkdjian',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Product_Image': 'https://fimgs.net/mdimg/perfume/375x500.46066.jpg',
	  'Sex': 'Unisex',
	  'Time': '17:03:56 18/10/2021',
	  'Year': '2017',
	  'Description': 'Baccarat Rouge 540 Extrait de Parfum by Maison Francis Kurkdjian is a Amber Floral fragrance for women and men. Baccarat Rouge 540 Extrait de Parfum was launched in 2017. The nose behind this fragrance is Francis Kurkdjian. Top notes are Bitter Almond and Saffron; middle notes are Egyptian Jasmine and Cedar; base notes are Ambergris, Woody Notes and Musk.',
	  'Reference': 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-Extrait-de-Parfum-46066.html',
	  'Color': (160, 96, 74)},
	 {'Brand_Name': 'Tiziana Terenzi',
	  'Product_Name': 'Spirito Fiorentino',
	  'Product_Image': 'https://fimgs.net/mdimg/perfume/375x500.52197.jpg',
	  'Sex': 'Unisex',
	  'Time': '17:04:04 18/10/2021',
	  'Year': '2019',
	  'Description': 'Spirito Fiorentino by Tiziana Terenzi is a Floral Woody Musk fragrance for women and men. This is a new fragrance. Spirito Fiorentino was launched in 2019. The nose behind this fragrance is Paolo Terenzi. Top notes are Saffron, Orange, Jasmine and Lily; middle notes are Ambergris, Ylang-Ylang, Lily-of-the-Valley and Magnolia; base notes are Leather, Birch, Precious Woods, Oakmoss, Musk and Sandalwood.',
	  'Reference': 'https://www.fragrantica.com/perfume/Tiziana-Terenzi/Spirito-Fiorentino-52197.html',
	  'Color': (240, 231, 221)}]

	read_fragrantics = pd.DataFrame(fragrantica_DF)

	get_brand_df = read_frame(getBrandData)

	concat_both_df = pd.concat([read_fragrantics,read_perfuma_df])

	merge_df = pd.merge(get_brand_df,concat_both_df,how='inner',left_on='b_name',right_on='Brand_Name').drop_duplicates(subset=['Brand_Name','Product_Name'],keep='first')

	tranpose_merge_df = merge_df.transpose()
	get_merge_data = tranpose_merge_df.to_dict()

	product_instances = [Products(

		b_name_id = value['id'],
		p_name = value['Product_Name'],
		p_image = value['Product_Image'],
		sex = value['Sex'],
		year = value['Year'],
		description = value['Description'],
		reference = value['Reference'],
		colour = value['Color'],
		time = value['Time']


		) for key,value in get_merge_data.items()]

	Products.objects.bulk_update_or_create(product_instances,['b_name_id','p_name','p_image','sex','year','description','reference',
		'colour','time'],match_field=['b_name_id','p_name','p_image','sex','year','description','reference',
		'colour','time'])


	main_accords = [{'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '100',
	  'Accords': 'fresh spicy'},
	 {'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '81.589',
	  'Accords': 'aromatic'},
	 {'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '74.1096',
	  'Accords': 'citrus'},
	 {'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '67.0137',
	  'Accords': 'woody'},
	 {'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '53.9726',
	  'Accords': 'rose'},
	 {'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '52.8219',
	  'Accords': 'leather'},
	 {'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '51.3835',
	  'Accords': 'herbal'},
	 {'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '50.137',
	  'Accords': 'amber'},
	 {'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '47.2123',
	  'Accords': 'powdery'},
	 {'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Score': '46.3014',
	  'Accords': 'musky'},
	 {'Product_Name': 'Burberry Her',
	 'Score': '100',
	 'Accords': 'fruity'},
	 {'Product_Name': 'Burberry Her',
	 'Score': '78.5138',
	 'Accords': 'sweet'},
	 {'Product_Name': 'Burberry Her',
	 'Score': '49.9018',
	 'Accords': 'woody'},
	 {'Product_Name': 'Burberry Her',
	 'Score': '48.5062',
	 'Accords': 'musky'},
	 {'Product_Name': 'Burberry Her',
	 'Score': '48.4131',
	 'Accords': 'powdery'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '100',
	  'Accords': 'amber'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '98.4877',
	  'Accords': 'almond'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '90.926',
	  'Accords': 'woody'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '81.2361',
	  'Accords': 'warm spicy'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '78.6543',
	  'Accords': 'animalic'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '71.0926',
	  'Accords': 'nutty'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '64.2438',
	  'Accords': 'fruity'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '64.0278',
	  'Accords': 'musky'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '61.0031',
	  'Accords': 'white floral'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Score': '57.3734',
	  'Accords': 'sweet'},
	 {'Product_Name': 'Spirito Fiorentino',
	 'Score': '100',
	 'Accords': 'leather'},
	 {'Product_Name': 'Spirito Fiorentino',
	 'Score': '79.004',
	 'Accords': 'woody'},
	 {'Product_Name': 'Spirito Fiorentino',
	  'Score': '69.8282',
	  'Accords': 'animalic'},
	 {'Product_Name': 'Spirito Fiorentino',
	  'Score': '62.4656',
	  'Accords': 'warm spicy'},
	 {'Product_Name': 'Spirito Fiorentino',
	  'Score': '62.4556',
	  'Accords': 'amber'},
	 {'Product_Name': 'Spirito Fiorentino',
	  'Score': '58.9496',
	  'Accords': 'smoky'},
	 {'Product_Name': 'Spirito Fiorentino',
	  'Score': '48.6319',
	  'Accords': 'white floral'},
	 {'Product_Name': 'Spirito Fiorentino',
	  'Score': '46.8288',
	  'Accords': 'mossy'},
	 {'Product_Name': 'Spirito Fiorentino',
	  'Score': '45.154',
	  'Accords': 'citrus'},
	 {'Product_Name': 'Spirito Fiorentino',
	  'Score': '45.0057',
	  'Accords': 'earthy'}]

	main_accords_df = pd.DataFrame(main_accords)
	get_product_Data = Products.objects.values('id','p_name')
	products_df = read_frame(get_product_Data)
	merge_accords_products = pd.merge(main_accords_df,products_df,how='inner',left_on='Product_Name',right_on='p_name')
	transpose_merge_accords_products = merge_accords_products.transpose()
	get_merge_accord_product_data = transpose_merge_accords_products.to_dict()

	main_accords_instances = [Main_accords(

		p_name_id = value['id'],
		score = value['Score'],
		accord = value['Accords']

		) for key,value in get_merge_accord_product_data.items()]
	Main_accords.objects.bulk_update_or_create(main_accords_instances,['p_name_id','score','accord'],match_field=['p_name_id','score','accord'])

	occasion = [{'Product_Name': 'XXX Charcoal'},
	 {'Sport': 5,
	  'Night Out': 7,
	  'Evening': 10,
	  'Leisure': 25,
	  'Daily': 25,
	  'Business': 27,
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Night Out': 27,
	  'Evening': 30,
	  'Leisure': 22,
	  'Daily': 9,
	  'Business': 12,
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Night Out': 31,
	  'Evening': 34,
	  'Leisure': 17,
	  'Daily': 11,
	  'Business': 8,
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'}]

	occasion_df = pd.DataFrame(occasion)
	occasion_df = occasion_df.fillna(0)
	merge_occasion_products = pd.merge(occasion_df,products_df,how='inner',left_on='Product_Name',right_on='p_name')
	transpose_merge_occasion_products = merge_occasion_products.transpose()
	get_transpose_merge_occasion_products = transpose_merge_occasion_products.to_dict()

	occasion_instances = [Occasion(

		p_name_id = value['id'],
		sport = int(value['Sport']),
		night_out = int(value['Night Out']),
		evening = int(value['Evening']),
		leisure = int(value['Leisure']),
		daily = int(value['Daily']),
		business = int(value['Business'])

		) for key,value in get_transpose_merge_occasion_products.items()]

	Occasion.objects.bulk_update_or_create(occasion_instances,['p_name_id','sport','night_out','evening','leisure','daily','business'],match_field = ['p_name_id','sport','night_out','evening','leisure','daily','business'] )

	similar_products = [{'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Name': 'L Heure Bleue',
	  'Link': 'https://www.parfumo.net/Perfumes/Guerlain/L_Heure_Bleue',
	  'Image': 'https://pimages.parfumo.de/3432_img-3986-guerlain-l-heure-bleue-eau-de-parfum.webp',
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Name': 'Fate Woman',
	  'Link': 'https://www.parfumo.net/Perfumes/Amouage/Fate_Woman',
	  'Image': 'https://pimages.parfumo.de/28129_img-6530-amouage-fate_woman_eau_de_parfum.webp',
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'},
	 {'Name': 'Fate Woman',
	  'Link': 'https://www.parfumo.net/Perfumes/Amouage/Fate_Woman',
	  'Image': 'https://pimages.parfumo.de/28129_img-6530-amouage-fate_woman_eau_de_parfum.webp',
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'},
	 {'Name': 'Fate Woman',
	  'Link': 'https://www.parfumo.net/Perfumes/Amouage/Fate_Woman',
	  'Image': 'https://pimages.parfumo.de/28129_img-6530-amouage-fate_woman_eau_de_parfum.webp',
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'},
	 {'Name': 'Fate Woman',
	  'Link': 'https://www.parfumo.net/Perfumes/Amouage/Fate_Woman',
	  'Image': 'https://pimages.parfumo.de/28129_img-6530-amouage-fate_woman_eau_de_parfum.webp',
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'},
	 {'Name': 'Fate Woman',
	  'Link': 'https://www.parfumo.net/Perfumes/Amouage/Fate_Woman',
	  'Image': 'https://pimages.parfumo.de/28129_img-6530-amouage-fate_woman_eau_de_parfum.webp',
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'},
	 {'Name': 'Fate Woman',
	  'Link': 'https://www.parfumo.net/Perfumes/Amouage/Fate_Woman',
	  'Image': 'https://pimages.parfumo.de/28129_img-6530-amouage-fate_woman_eau_de_parfum.webp',
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'},
	 {'Name': 'Fate Woman',
	  'Link': 'https://www.parfumo.net/Perfumes/Amouage/Fate_Woman',
	  'Image': 'https://pimages.parfumo.de/28129_img-6530-amouage-fate_woman_eau_de_parfum.webp',
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'},
	 {'Name': 'Fate Woman',
	  'Link': 'https://www.parfumo.net/Perfumes/Amouage/Fate_Woman',
	  'Image': 'https://pimages.parfumo.de/28129_img-6530-amouage-fate_woman_eau_de_parfum.webp',
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'}]


	frag_similar_products = [{'Name': 'Pegaso Etro',
	  'Link': 'https://www.fragrantica.com/perfume/Etro/Pegaso-5656.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.5656.jpg',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'Outrageous! Limited Edition 2017 Frederic Malle',
	  'Link': 'https://www.fragrantica.com/perfume/Frederic-Malle/Outrageous-Limited-Edition-2017-43456.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.43456.jpg',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'Fougere Furieuse Mugler',
	  'Link': 'https://www.fragrantica.com/perfume/Mugler/Fougere-Furieuse-25094.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.25094.jpg',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'Gris Montaigne Dior',
	  'Link': 'https://www.fragrantica.com/perfume/Dior/Gris-Montaigne-17842.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.17842.jpg',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'In The Mood For Love Gianfranco Ferre',
	  'Link': 'https://www.fragrantica.com/perfume/Gianfranco-Ferre/In-The-Mood-For-Love-6530.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.6530.jpg',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'Jardin d’Amalfi Creed',
	  'Link': 'https://www.fragrantica.com/perfume/Creed/Jardin-d-Amalfi-13389.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.13389.jpg',
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Name': 'Baccarat Rouge 540 Maison Francis Kurkdjian',
	  'Link': 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-33519.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.33519.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Cloud Ariana Grande',
	  'Link': 'https://www.fragrantica.com/perfume/Ariana-Grande/Cloud-50384.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.50384.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Burberry Her Intense Burberry',
	  'Link': 'https://www.fragrantica.com/perfume/Burberry/Burberry-Her-Intense-56761.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.56761.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Baccarat Rouge 540 Extrait de Parfum Maison Francis Kurkdjian',
	  'Link': 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-Extrait-de-Parfum-46066.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.46066.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Cosmic  Agent Provocateur',
	  'Link': 'https://www.fragrantica.com/perfume/Agent-Provocateur/Cosmic-55451.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.55451.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Liz O Boticário',
	  'Link': 'https://www.fragrantica.com/perfume/O-Boticario/Liz-62270.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.62270.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Burberry Her Blossom Burberry',
	  'Link': 'https://www.fragrantica.com/perfume/Burberry/Burberry-Her-Blossom-54574.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.54574.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Rouge 540 Limited Edition Baccarat',
	  'Link': 'https://www.fragrantica.com/perfume/Baccarat/Rouge-540-Limited-Edition-29224.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.29224.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Daisy Eau So Intense Marc Jacobs',
	  'Link': 'https://www.fragrantica.com/perfume/Marc-Jacobs/Daisy-Eau-So-Intense-65666.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.65666.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Her Jequiti',
	  'Link': 'https://www.fragrantica.com/perfume/Jequiti/Her-62064.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.62064.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Lyra Eudora',
	  'Link': 'https://www.fragrantica.com/perfume/Eudora/Lyra-63599.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.63599.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Rouge Royal Princesse Marina De Bourbon',
	  'Link': 'https://www.fragrantica.com/perfume/Princesse-Marina-De-Bourbon/Rouge-Royal-1505.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.1505.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Greenwich Village Bond No 9',
	  'Link': 'https://www.fragrantica.com/perfume/Bond-No-9/Greenwich-Village-54157.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.54157.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Pure Sugar Cosmopolitan',
	  'Link': 'https://www.fragrantica.com/perfume/Cosmopolitan/Pure-Sugar-56260.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.56260.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Stramonio V Canto',
	  'Link': 'https://www.fragrantica.com/perfume/V-Canto/Stramonio-49525.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.49525.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Mauboussin in Red Mauboussin',
	  'Link': 'https://www.fragrantica.com/perfume/Mauboussin/Mauboussin-in-Red-57406.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.57406.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Red Temptation For Her Zara',
	  'Link': 'https://www.fragrantica.com/perfume/Zara/Red-Temptation-For-Her-63264.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.63264.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Tinharé Le Couvent Maison de Parfum',
	  'Link': 'https://www.fragrantica.com/perfume/Le-Couvent-Maison-de-Parfum/Tinhare-53524.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.53524.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': '.SE Swedish Experience Blazing Warmth Oriflame',
	  'Link': 'https://www.fragrantica.com/perfume/Oriflame/SE-Swedish-Experience-Blazing-Warmth-68317.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.68317.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Capricho Hello Stars O Boticário',
	  'Link': 'https://www.fragrantica.com/perfume/O-Boticario/Capricho-Hello-Stars-67917.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.67917.jpg',
	  'Product_Name': 'Burberry Her'},
	 {'Name': 'Baccarat Rouge 540 Maison Francis Kurkdjian',
	  'Link': 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-33519.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.33519.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Burberry Her Burberry',
	  'Link': 'https://www.fragrantica.com/perfume/Burberry/Burberry-Her-51694.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.51694.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Spirito Fiorentino Tiziana Terenzi',
	  'Link': 'https://www.fragrantica.com/perfume/Tiziana-Terenzi/Spirito-Fiorentino-52197.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.52197.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Cloud Ariana Grande',
	  'Link': 'https://www.fragrantica.com/perfume/Ariana-Grande/Cloud-50384.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.50384.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Amber Oud Rouge Al Haramain Perfumes',
	  'Link': 'https://www.fragrantica.com/perfume/Al-Haramain-Perfumes/Amber-Oud-Rouge-66100.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.66100.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Stramonio V Canto',
	  'Link': 'https://www.fragrantica.com/perfume/V-Canto/Stramonio-49525.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.49525.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Ana Abiyedh Rouge Lattafa Perfumes',
	  'Link': 'https://www.fragrantica.com/perfume/Lattafa-Perfumes/Ana-Abiyedh-Rouge-63062.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.63062.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Tinharé Le Couvent Maison de Parfum',
	  'Link': 'https://www.fragrantica.com/perfume/Le-Couvent-Maison-de-Parfum/Tinhare-53524.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.53524.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Interplay Extrait Alexandria Fragrances',
	  'Link': 'https://www.fragrantica.com/perfume/Alexandria-Fragrances/Interplay-Extrait-52000.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.52000.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Instant Crush Mancera',
	  'Link': 'https://www.fragrantica.com/perfume/Mancera/Instant-Crush-54885.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.54885.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Aristocrat for Her Ajmal',
	  'Link': 'https://www.fragrantica.com/perfume/Ajmal/Aristocrat-for-Her-50024.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.50024.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Sensual Instinct Montale',
	  'Link': 'https://www.fragrantica.com/perfume/Montale/Sensual-Instinct-53675.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.53675.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Liwa WIDIAN',
	  'Link': 'https://www.fragrantica.com/perfume/WIDIAN/Liwa-44112.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.44112.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Night Pour Homme V Zara',
	  'Link': 'https://www.fragrantica.com/perfume/Zara/Night-Pour-Homme-V-62365.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.62365.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Love Game Patrice Martin',
	  'Link': 'https://www.fragrantica.com/perfume/Patrice-Martin/Love-Game-59452.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.59452.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Red Temptation For Him Zara',
	  'Link': 'https://www.fragrantica.com/perfume/Zara/Red-Temptation-For-Him-63273.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.63273.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Red Potion The Merchant of Venice',
	  'Link': 'https://www.fragrantica.com/perfume/The-Merchant-of-Venice/Red-Potion-55111.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.55111.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Zeta Morph',
	  'Link': 'https://www.fragrantica.com/perfume/Morph/Zeta-51603.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.51603.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Cloud Intense Ariana Grande',
	  'Link': 'https://www.fragrantica.com/perfume/Ariana-Grande/Cloud-Intense-69296.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.69296.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Trajan Electimuss',
	  'Link': 'https://www.fragrantica.com/perfume/Electimuss/Trajan-61808.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.61808.jpg',
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Name': 'Baccarat Rouge 540 Maison Francis Kurkdjian',
	  'Link': 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-33519.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.33519.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Baccarat Rouge 540 Extrait de Parfum Maison Francis Kurkdjian',
	  'Link': 'https://www.fragrantica.com/perfume/Maison-Francis-Kurkdjian/Baccarat-Rouge-540-Extrait-de-Parfum-46066.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.46066.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Stramonio V Canto',
	  'Link': 'https://www.fragrantica.com/perfume/V-Canto/Stramonio-49525.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.49525.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Sensual Instinct Montale',
	  'Link': 'https://www.fragrantica.com/perfume/Montale/Sensual-Instinct-53675.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.53675.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Après l’Amour Thomas Kosmala',
	  'Link': 'https://www.fragrantica.com/perfume/Thomas-Kosmala/Apres-l-Amour-53742.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.53742.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': "Bade'e Al Oud Oud for Glory Lattafa Perfumes",
	  'Link': 'https://www.fragrantica.com/perfume/Lattafa-Perfumes/Bade-e-Al-Oud-Oud-for-Glory-64948.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.64948.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Cloud Ariana Grande',
	  'Link': 'https://www.fragrantica.com/perfume/Ariana-Grande/Cloud-50384.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.50384.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Instant Crush Mancera',
	  'Link': 'https://www.fragrantica.com/perfume/Mancera/Instant-Crush-54885.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.54885.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Tinharé Le Couvent Maison de Parfum',
	  'Link': 'https://www.fragrantica.com/perfume/Le-Couvent-Maison-de-Parfum/Tinhare-53524.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.53524.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Opulent Musk Lattafa Perfumes',
	  'Link': 'https://www.fragrantica.com/perfume/Lattafa-Perfumes/Opulent-Musk-67940.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.67940.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Dream Moon Pacifica',
	  'Link': 'https://www.fragrantica.com/perfume/Pacifica/Dream-Moon-64941.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.64941.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Absolutio Navitus Parfums',
	  'Link': 'https://www.fragrantica.com/perfume/Navitus-Parfums/Absolutio-60620.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.60620.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Liwa WIDIAN',
	  'Link': 'https://www.fragrantica.com/perfume/WIDIAN/Liwa-44112.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.44112.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Elfe d’Or Les Contes',
	  'Link': 'https://www.fragrantica.com/perfume/Les-Contes/Elfe-d-Or-63862.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.63862.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Sunset Riot Allsaints',
	  'Link': 'https://www.fragrantica.com/perfume/Allsaints/Sunset-Riot-61460.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.61460.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Gharaam Swiss Arabian',
	  'Link': 'https://www.fragrantica.com/perfume/Swiss-Arabian/Gharaam-56231.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.56231.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'By the Fireplace Maison Martin Margiela',
	  'Link': 'https://www.fragrantica.com/perfume/Maison-Martin-Margiela/By-the-Fireplace-31623.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.31623.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'TriBeCa Bond No 9',
	  'Link': 'https://www.fragrantica.com/perfume/Bond-No-9/TriBeCa-59904.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.59904.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Amber Oud Rouge Al Haramain Perfumes',
	  'Link': 'https://www.fragrantica.com/perfume/Al-Haramain-Perfumes/Amber-Oud-Rouge-66100.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.66100.jpg',
	  'Product_Name': 'Spirito Fiorentino'},
	 {'Name': 'Mandragola V Canto',
	  'Link': 'https://www.fragrantica.com/perfume/V-Canto/Mandragola-37746.html',
	  'Image': 'https://fimgs.net/mdimg/perfume/s.37746.jpg',
	  'Product_Name': 'Spirito Fiorentino'}]

	similar_products_df = pd.DataFrame(similar_products)
	frag_similar_products_df = pd.DataFrame(frag_similar_products)
	concat_both = pd.concat([similar_products_df,frag_similar_products_df])

	similar_products_merge = pd.merge(concat_both,products_df,how='inner',left_on='Product_Name',right_on='p_name').drop_duplicates()
	transpose_similar_products_merge = similar_products_merge.transpose()
	get_transpose_similar_products_merge = transpose_similar_products_merge.to_dict()
	similar_products_instance = [Similar_products(
		p_name_id = value['id'],
		link = value['Link'],
		image = value['Image'],
		name = value['Name']
  		) for key,value in get_transpose_similar_products_merge.items()]
	Similar_products.objects.bulk_update_or_create(similar_products_instance,['p_name_id','link','image','name'],match_field=['p_name_id','link','image','name'])

	audience = [{'Product_Name': 'XXX Charcoal'},
	 {'Young': 19,
	  'Men': 27,
	  'Women': 54,
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Old': 22,
	  'Young': 12,
	  'Men': 28,
	  'Women': 39,
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Old': 26,
	  'Young': 5,
	  'Men': 17,
	  'Women': 52,
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'}]

	audience_df = pd.DataFrame(audience)

	audience_data = pd.merge(audience_df,products_df,how='inner',left_on='Product_Name',right_on='p_name').fillna(0)
	transpose_audience_data = audience_data.transpose()
	get_transpose_audience_data = transpose_audience_data.to_dict()

	audience_instances = [Audience(
		p_name_id = value['id'],
		young = int(value['Young']),
		old = int(value['Old']),
		men = int(value['Men']),
		women = int(value['Women']),
		) for key,value in get_transpose_audience_data.items()]

	Audience.objects.bulk_update_or_create(audience_instances,['p_name_id','young','old','men','women'],match_field=['p_name_id','young','old','men','women'])


	perfuma_season = [{'Product_Name': 'XXX Charcoal'},
	 {'Spring': 39,
	  'Winter': 10,
	  'Fall': 18,
	  'Summer': 33,
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Spring': 25,
	  'Winter': 26,
	  'Fall': 31,
	  'Summer': 18,
	  'Product_Name': 'Mitsouko  1919 Ext'},
	 {'Spring': 21,
	  'Winter': 32,
	  'Fall': 35,
	  'Summer': 12,
	  'Product_Name': 'Jubilation 25 Woman  2007 Eau de Pa'}]

	fragrantica_season = [{'Product_Name': "L'Anonyme ou OP-1475-A",
	  'Winter': '13.6364',
	  'Spring': '79.5455',
	  'Summer': '63.6364',
	  'Fall': '45.4545',
	  'Day': '100',
	  'Night': '20.4545'},
	 {'Product_Name': 'Burberry Her',
	  'Winter': '40.1918',
	  'Spring': '88.6661',
	  'Summer': '60.0697',
	  'Fall': '60.5057',
	  'Day': '100',
	  'Night': '28.5092'},
	 {'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum',
	  'Winter': '95.4119',
	  'Spring': '72.367',
	  'Summer': '38.5819',
	  'Fall': '100',
	  'Day': '87.9041',
	  'Night': '95.7247'},
	 {'Product_Name': 'Spirito Fiorentino',
	  'Winter': '73.2394',
	  'Spring': '64.7887',
	  'Summer': '45.0704',
	  'Fall': '100',
	  'Day': '69.7183',
	  'Night': '92.2535'}]


	perfuma_season_df = pd.DataFrame(perfuma_season)
	fragrantica_season_df = pd.DataFrame(fragrantica_season)
	concat_both_season = pd.concat([fragrantica_season_df,perfuma_season_df]).drop_duplicates(subset=['Product_Name'])
	merge_season_data = pd.merge(concat_both_season,products_df,how='inner',left_on='Product_Name',right_on='p_name')
	transpose_concat_both_season = merge_season_data.transpose()
	get_transpose_concat_both_season = transpose_concat_both_season.to_dict()

	seasons_instances = [Seasons(
		p_name_id = value['id'],
		winter = value['Winter'],
		summer = value['Summer'],
		spring = value['Spring'],
		fall = value['Fall'],
		day = value['Day'],
		night = value['Night'],

		) for key,value in get_transpose_concat_both_season.items()]

	Seasons.objects.bulk_update_or_create(seasons_instances,['p_name_id','winter','summer','spring','fall','day','night'],match_field=['p_name_id','winter','summer','spring','fall','day','night'])

	perfuma_notes = [{'Others': ['Persian amber', 'White pepper', 'Musk'],
	  'Product_Name': "Oriental Essence - Roi d'Orient"},
	 {'Top_Note': ['Bergamot'],
	  'Middle_Note': ['Geranium'],
	  'Base_Note': ['Woods', 'White amber', 'Suede'],
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Top_Note': ['Fig', 'Orange'],
	  'Middle_Note': ['Peach', 'Mango', 'Cyclamen'],
	  'Base_Note': ['Coconut milk', 'Musk'],
	  'Product_Name': "Fico d'India"},
	 {'Top_Note': ['Iris', 'Ambrette', 'Juniper berry', 'Star anise'],
	  'Middle_Note': ['Oud', 'Clove', 'Rose'],
	  'Base_Note': ['Frankincense', 'Vetiver', 'Patchouli'],
	  'Product_Name': 'Iris Nazarena'}]

	fragrantica_notes = [{'Top_Note': ['Bergamot'],
	  'Middle_Note': ['Geranium'],
	  'Base_Note': ['Suede', 'Woody Notes', 'Amber'],
	  'Others': [],
	  'Product_Name': "L'Anonyme ou OP-1475-A"},
	 {'Top_Note': ['Sour Cherry',
	   'Strawberry',
	   'Mandarin Orange',
	   'Raspberry',
	   'Blackberry',
	   'Black Currant',
	   'Lemon'],
	  'Middle_Note': ['Violet', 'Jasmine'],
	  'Base_Note': ['Cashmeran',
	   'Oakmoss',
	   'Vanilla',
	   'Patchouli',
	   'Woody Notes',
	   'Amber',
	   'Musk'],
	  'Others': [],
	  'Product_Name': 'Burberry Her'},
	 {'Top_Note': ['Saffron', 'Almond'],
	  'Middle_Note': ['Jasmine', 'Cedar'],
	  'Base_Note': ['Woody Notes', 'Ambergris', 'Musk'],
	  'Others': [],
	  'Product_Name': 'Baccarat Rouge 540 Extrait de Parfum'},
	 {'Top_Note': ['Orange', 'Lily', 'Saffron', 'Jasmine'],
	  'Middle_Note': ['Ylang Ylang',
	   'Magnolia',
	   'Lily of the Valley',
	   'Ambergris'],
	  'Base_Note': ['Birch',
	   'Leather',
	   'Oakmoss',
	   'Sandalwood',
	   'Woody Notes',
	   'Musk'],
	  'Others': [],
	  'Product_Name': 'Spirito Fiorentino'}]
	perfuma_notes_df = pd.DataFrame(perfuma_notes)
	fragrantica_notes_df = pd.DataFrame(fragrantica_notes)
	concat_notes = pd.concat([fragrantica_notes_df,perfuma_notes_df])
	merge_notes =pd.merge(concat_notes,products_df,how='inner',left_on='Product_Name',right_on='p_name').drop_duplicates(subset=['Product_Name'])
	transpose_merge_notes = merge_notes.transpose()
	get_transpose_merge_notes = transpose_merge_notes.to_dict()

	notes_instances = [Product_notes(
		p_name_id = value['id'],
		top_note = value['Top_Note'],
		middle_note = value['Middle_Note'],
		base_note = value['Base_Note'],
		others = value['Others']

		)for key,value in get_transpose_merge_notes.items()]

	Product_notes.objects.bulk_update_or_create(notes_instances,['p_name_id','top_note','middle_note','base_note','others'],match_field=['p_name_id','top_note','middle_note','base_note','others'])

	# getBrand = Brand.objects.all()
	# BrandDF = read_frame(getBrand)
	# getProduct = pd.DataFrame(product)
	# # print(BrandDF)
	# df_join = pd.merge(getProduct, BrandDF, how="left", left_on='Brand_Name',
 #                          right_on='b_name')
	# print(df_join)
	return HttpResponse('Data saved Successfully !')